apiVersion: apps/v1
kind: Deployment
metadata:
  name: comfyui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comfyui
  template:
    metadata:
      labels:
        app: comfyui
    spec:
      containers:
      - name: comfyui-container
        image: obeliks/comfyui:sha-ebf5c41-cu121
        securityContext:
          runAsUser: 0  # 0 = root
        ports:
        - containerPort: 8188  # Port par défaut de ComfyUI
        resources:
          limits:
            nvidia.com/gpu: 1  # Demande une GPU
        volumeMounts:
        - name: models-volume
          mountPath: /app/custom_nodes
          subPath: custom_nodes_volume
        - name: models-volume
          mountPath: /app/output  # Chemin où ComfyUI stocke les modèles
          subPath: output_volume
      initContainers:
      # InitContainer pour le clonage des dépôts git
      - name: git-init
        image: debian:latest  # Utilise une image Debian
        command:
        - /bin/sh
        - -c
        - |
          apt-get update && apt-get install -y git 
          mkdir -p /app/custom_nodes  # Assure que le répertoire cible existe
          git clone https://github.com/ltdrdata/ComfyUI-Manager.git /app/custom_nodes/ComfyUI-Manager
          git clone https://github.com/cubiq/ComfyUI_IPAdapter_plus.git /app/custom_nodes/ComfyUI_IPAdapter_plus
        volumeMounts:
        - name: models-volume
          mountPath: /app/custom_nodes  # Monte le volume pour stocker les fichiers clonés
          subPath: custom_nodes_volume
      # InitContainer pour la configuration avec MinIO
      - name: minio-init
        image: minio/mc
        command:
        - /bin/sh
        - -c
        - |
          mc alias set s3 https://$AWS_S3_ENDPOINT $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
          mkdir -p /app/output/checkpoints
          mc cp s3/cguillo/model_stable_diff.safetensors /app/output/checkpoints/model.safetensors
        env:
        - name: AWS_S3_ENDPOINT
          value: minio.lab.sspcloud.fr
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: sa-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: sa-secret
              key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
        - name: models-volume
          mountPath: /app/output  # Monte le volume pour accéder aux modèles
          subPath: output_volume
      volumes:
      - name: models-volume
        persistentVolumeClaim:
          claimName: comfyui-models-pvc
