apiVersion: apps/v1
kind: Deployment
metadata:
  name: comfyui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comfyui
  template:
    metadata:
      labels:
        app: comfyui
    spec:
      containers:
      - name: comfyui-container
        image: obeliks/comfyui:sha-ebf5c41-cu121
        securityContext:
          runAsUser: 0  # 0 = root
        ports:
        - containerPort: 8188  # Port par défaut de ComfyUI
        resources:
          limits:
            nvidia.com/gpu: 1  # Demande une GPU
        volumeMounts:
        - name: models-volume
          mountPath: /app/output/  # Chemin où ComfyUI stocke les modèles
        
      initContainers:
      - name: minio-init
        image: minio/mc
        command:
        - /bin/sh
        - -c
        - |
          mc alias set s3 https://$AWS_S3_ENDPOINT $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
          mkdir -p /app/output/checkpoints 
          mc cp s3/cguillo/model_stable_diff.safetensors /app/output/checkpoints/model.safetensors
        env:
        - name: AWS_S3_ENDPOINT
          value: minio.lab.sspcloud.fr
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: sa-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: sa-secret
              key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
        - name: models-volume
          mountPath: /app/output/  # Monter le volume pour permettre l'accès aux modèles
      volumes:
      - name: models-volume
        persistentVolumeClaim:
          claimName: comfyui-models-pvc
