apiVersion: apps/v1
kind: Deployment
metadata:
  name: comfyui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comfyui
  template:
    metadata:
      labels:
        app: comfyui
    spec:
      containers:
      - name: comfyui-container
        
        image: obeliks/comfyui:sha-ebf5c41-cu121
        securityContext:
          runAsUser: 0  # 0 = root
        ports:
        - containerPort: 8188  # Port par défaut de ComfyUI
        resources:
          limits:
            nvidia.com/gpu: 1  # Demande une GPU
        volumeMounts:
        - name: models-volume
          mountPath: /app/custom_nodes
          subPath: custom_nodes_paths
        - name: models-volume
          mountPath: /app/models  # Chemin où ComfyUI stocke les modèles
          subPath: models_path
        - name: configs
          mountPath: /app/extra_model_paths.yaml
          subPath: extra_model_paths.yaml
      initContainers:
      # InitContainer pour le clonage des dépôts git
      - name: git-init
        image: debian:latest  # Utilise une image Debian
        command:
        - /bin/sh
        - -c
        - |
          apt-get update && apt-get install -y git 
          mkdir -p /app/custom_nodes  # Assure que le répertoire cible existe
          if [ ! -d "/app/custom_nodes/ComfyUI-Manager" ]; then
            git clone https://github.com/ltdrdata/ComfyUI-Manager.git /app/custom_nodes/ComfyUI-Manager
          else
            echo "ComfyUI-Manager existe déjà, pas besoin de cloner."
          fi
          
          if [ ! -d "/app/custom_nodes/ComfyUI_IPAdapter_plus" ]; then
            git clone https://github.com/cubiq/ComfyUI_IPAdapter_plus.git /app/custom_nodes/ComfyUI_IPAdapter_plus
          else
            echo "ComfyUI_IPAdapter_plus existe déjà, pas besoin de cloner."
          fi
        
        volumeMounts:
        - name: models-volume
          mountPath: /app/custom_nodes  # Monte le volume pour stocker les fichiers clonés
          subPath: custom_nodes_paths
      # InitContainer pour la configuration avec MinIO
      - name: minio-init
        image: minio/mc
        command:
        - /bin/sh
        - -c
        - |
          mc alias set s3 https://$AWS_S3_ENDPOINT $AWS_ACCESS_KEY_ID $AWS_SECRET_ACCESS_KEY
          mkdir -p /app/models/checkpoints
          # if [ ! -f /app/models/checkpoints/sd15.safetensors ]; then
          #   mc cp s3/cguillo/sd15.safetensors /app/models/checkpoints/sd15.safetensors
          # fi
          if [ ! -f /app/models/checkpoints/sdXL.safetensors ]; then
            mc cp s3/cguillo/sdXL.safetensors /app/models/checkpoints/sdXL.safetensors
          fi
          # if [ ! -f /app/models/loras/RMSDXL_Photo.safetensors ]; then
          #   mc cp s3/cguillo/RMSDXL_Photo.safetensors /app/models/loras/RMSDXL_Photo.safetensors
          # fi
          # if [ ! -f /app/models/checkpoints/realismEngineSDXL_v30VAE.safetensors ]; then
          #   mc cp s3/cguillo/realismEngineSDXL_v30VAE.safetensors /app/models/checkpoints/realismEngineSDXL_v30VAE.safetensors
          # fi
          # if [ ! -f /app/models/checkpoints/realvisxlV50_v50Bakedvae.safetensors ]; then
          #   mc cp s3/cguillo/realvisxlV50_v50Bakedvae.safetensors /app/models/checkpoints/realvisxlV50_v50Bakedvae.safetensors
          # fi
          
        env:
        - name: AWS_S3_ENDPOINT
          value: minio.lab.sspcloud.fr
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: sa-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: sa-secret
              key: AWS_SECRET_ACCESS_KEY
        volumeMounts:
        - name: models-volume
          mountPath: /app/models  # Monte le volume pour accéder aux modèles
          subPath: models_path
      volumes:
      - name: models-volume
        persistentVolumeClaim:
          claimName: comfyui-models-pvc
          volumes:
      - name: configs
        configMap:
          name: vol-config-extra-models-paths
